version: 2
jobs:
  build:
    working_directory: ~/FEC
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Run npm install
          command: npm install
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test
