version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install --force
      - run: sudo npm install -g npm@latest --force
      - run: server-dev
      - run: client-dev
workflows:
  setup-and-run:
    jobs:
        - node/test