version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  node-install:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install-packages
workflows:
  setup-client-server:
    jobs:
        - node/run:
            pkg-manager: npm 
            npm-run: server-dev
        - node/run:
            pkg-manager: npm
            npm-run: client-dev
  node-tests:
    jobs:
      - node/test