version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  setup-and-run:
    jobs:
        - node/run:
            pkg-manager: npm 
            npm-run: server-dev
        - node/run:
            pkg-manager: npm
            npm-run: client-dev
        - node/test